package:
    name: coecms-util
    version: {{ GIT_DESCRIBE_TAG }}

source:
    git_url: ../

build:
    number: {{ GIT_DESCRIBE_NUMBER }}
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    run:
        - python

test:
    requries:
        - pytest
    source_files:
        - setup.cfg
        - test
    commands:
        - py.test
    imports:
        - coecms
