package:
    name: coecms-util
    version: {{ GIT_DESCRIBE_TAG }}

source:
    git_url: ../

build:
    number: {{ GIT_DESCRIBE_NUMBER }}
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
    run:
        - python
        - cfunits
        - mule
        - xarray
        - dask

test:
    requires:
        - pytest
    source_files:
        - setup.cfg
        - test
    commands:
        - py.test
    imports:
        - coecms

about:
    home: https://github.com/coecms/coecms-util
    license: Apache 2.0
    license_file: LICENSE
