package:
    name: coecms-util
    version: {{ GIT_DESCRIBE_TAG }}

source:
    git_url: ../

build:
    number: {{ GIT_DESCRIBE_NUMBER }}
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
    run:
        - python
        - cdo>=1.9.4
        - cfunits
        - dask>=1.2.0
        - mule
        - netcdf4
        - numpy
        - scipy
        - sparse
        - xarray
        - whichcraft # [py2k]
        - hdf5>=1.10.1 # Missing dependency of CDO

test:
    requires:
        - pytest
        - esmf
    source_files:
        - setup.cfg
        - test
    commands:
        - py.test
    imports:
        - coecms

about:
    home: https://github.com/coecms/coecms-util
    license: APACHE
    license_file: LICENSE
